DROP TABLE IF EXISTS etf_index_config CASCADE;
CREATE TABLE IF NOT EXISTS etf_index_config (
  id SERIAL NOT NULL,
  url VARCHAR(512) NOT NULL,
  geographic_exposure VARCHAR(128) NOT NULL,
  suspended BOOLEAN DEFAULT FALSE,
  CONSTRAINT etf_index_config_pkey PRIMARY KEY (id),
  CONSTRAINT etf_index_config_url_ukey UNIQUE (url)
);

INSERT INTO etf_index_config (url, geographic_exposure) VALUES
  ('https://www.ishares.com/us/products/239665/ishares-msci-japan-etf', 'Japan'),
  ('https://www.ishares.com/us/products/239612/ishares-msci-brazil-capped-etf', 'Brazil'),
  ('https://www.ishares.com/us/products/239659/ishares-msci-india-etf', 'India'),
  ('https://www.ishares.com/us/products/239536/ishares-china-largecap-etf', 'China'),
  ('https://www.ishares.com/us/products/239650/ishares-msci-germany-etf', 'Germany'),
  ('https://www.ishares.com/us/products/239615/ishares-msci-canada-etf', 'Canada'),
  ('https://www.ishares.com/us/products/239681/ishares-msci-south-korea-capped-etf', 'South Korea'),
  ('https://www.ishares.com/us/products/239686/ishares-msci-taiwan-etf', 'Taiwan'),
  ('https://www.ishares.com/us/products/239619/ishares-msci-china-etf', 'China'),
  ('https://www.ishares.com/us/products/239690/ishares-msci-united-kingdom-etf', 'United Kingdom'),
  ('https://www.ishares.com/us/products/239657/ishares-msci-hong-kong-etf', 'Hong Kong'),
  ('https://www.ishares.com/us/products/239607/ishares-msci-australia-etf', 'Australia'),
  ('https://www.ishares.com/us/products/239670/ishares-msci-mexico-capped-etf', 'Mexico'),
  ('https://www.ishares.com/us/products/239685/ishares-msci-switzerland-capped-etf', 'Switzerland'),
  ('https://www.ishares.com/us/products/239758/ishares-india-50-etf', 'India'),
  ('https://www.ishares.com/us/products/239683/ishares-msci-spain-capped-etf', 'Spain'),
  ('https://www.ishares.com/us/products/239678/ishares-msci-singapore-etf', 'Singapore'),
  ('https://www.ishares.com/us/products/239664/ishares-msci-italy-capped-etf', 'Italy'),
  ('https://www.ishares.com/us/products/239661/ishares-msci-indonesia-etf', 'Indonesia'),
  ('https://www.ishares.com/us/products/239677/ishares-msci-russia-capped-etf', 'Russia'),
  ('https://www.ishares.com/us/products/239618/ishares-msci-chile-capped-etf', 'Chile'),
  ('https://www.ishares.com/us/products/239680/ishares-msci-south-africa-etf', 'South Africa'),
  ('https://www.ishares.com/us/products/239688/ishares-msci-thailand-capped-etf', 'Thailand'),
  ('https://www.ishares.com/us/products/239689/ishares-msci-turkey-etf', 'Turkey'),
  ('https://www.ishares.com/us/products/239684/ishares-msci-sweden-etf', 'Sweden'),
  ('https://www.ishares.com/us/products/239648/ishares-msci-france-etf', 'France'),
  ('https://www.ishares.com/us/products/239669/ishares-msci-malaysia-etf', 'Malaysia'),
  ('https://www.ishares.com/us/products/239671/ishares-msci-netherlands-etf', 'Netherlands'),
  ('https://www.ishares.com/us/products/239676/ishares-msci-poland-capped-etf', 'Poland'),
  ('https://www.ishares.com/us/products/239675/ishares-msci-philippines-etf', 'Philippines'),
  ('https://www.ishares.com/us/products/239672/ishares-msci-new-zealand-capped-etf', 'New Zealand'),
  ('https://www.ishares.com/us/products/239666/ishares-msci-japan-smallcap-etf', 'Japan'),
  ('https://www.ishares.com/us/products/239662/ishares-msci-ireland-capped-etf', 'Ireland'),
  ('https://www.ishares.com/us/products/239610/ishares-msci-belgium-capped-etf', 'Belgium'),
  ('https://www.ishares.com/us/products/239663/ishares-msci-israel-capped-etf', 'Israel'),
  ('https://www.ishares.com/us/products/239609/ishares-msci-austria-capped-etf', 'Austria'),
  ('https://www.ishares.com/us/products/239660/ishares-msci-india-smallcap-etf', 'India'),
  ('https://www.ishares.com/us/products/239621/ishares-msci-denmark-capped-etf', 'Denmark'),
  ('https://www.ishares.com/us/products/264613/ishares-msci-japan-minimum-volatility-etf', 'Japan'),
  ('https://www.ishares.com/us/products/239613/ishares-msci-brazil-smallcap-etf', 'Brazil'),
  ('https://www.ishares.com/us/products/264273/ishares-msci-qatar-capped-etf', 'Qatar'),
  ('https://www.ishares.com/us/products/239647/ishares-msci-finland-capped-etf', 'Finland'),
  ('https://www.ishares.com/us/products/239673/ishares-msci-norway-capped-etf', 'Norway'),
  ('https://www.ishares.com/us/products/239691/ishares-msci-united-kingdom-smallcap-etf', 'United Kingdom'),
  ('https://www.ishares.com/us/products/239651/ishares-msci-germany-smallcap-etf', 'Germany'),
  ('https://www.ishares.com/us/products/239620/ishares-msci-china-smallcap-etf', 'China'),
  ('https://www.ishares.com/us/products/254562/ishares-msci-colombia-capped-etf', 'Colombia'),
  ('https://www.ishares.com/us/products/273318/ishares-msci-china-a-etf', 'China'),
  ('https://www.ishares.com/us/products/271542/ishares-msci-saudi-arabia-capped-etf', 'Saudi Arabia'),
  ('https://www.ishares.com/us/products/239726/ishares-core-sp-500-etf', 'United States'),
  ('https://www.ishares.com/us/products/239763/ishares-core-sp-midcap-etf', 'United States'),
  ('https://www.ishares.com/us/products/239774/ishares-core-sp-smallcap-etf', 'United States'),
  ('https://www.ishares.com/us/products/239699/ishares-nasdaq-biotechnology-etf', 'United States'),
  ('https://www.ishares.com/us/products/239522/ishares-us-technology-etf', 'United States'),
  ('https://www.ishares.com/us/products/239563/ishares-high-dividend-etf', 'United States'),
  ('https://www.ishares.com/us/products/239513/ishares-dow-jones-us-etf', 'United States'),
  ('https://www.ishares.com/us/products/239467/ishares-tips-bond-etf', 'United States'),
  ('https://www.ishares.com/us/products/239451/ishares-13-year-credit-bond-etf', 'United States'),
  ('https://www.ishares.com/us/products/239423/ishares-10-year-credit-bond-etf', 'United States'),
  ('https://www.ishares.com/us/products/239452/ishares-13-year-treasury-bond-etf', 'United States'),
  ('https://www.ishares.com/us/products/239455/ishares-37-year-treasury-bond-etf', 'United States'),
  ('https://www.ishares.com/us/products/239456/ishares-710-year-treasury-bond-etf', 'United States'),
  ('https://www.ishares.com/us/products/239453/ishares-1020-year-treasury-bond-etf', 'United States'),
  ('https://www.ishares.com/us/products/239454/ishares-20-year-treasury-bond-etf', 'United States'),
  ('https://www.ishares.com/us/products/239520/ishares-us-real-estate-etf', 'United States')
ON CONFLICT DO NOTHING;
